//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.02 at 09:04:17 PM EDT 
//


package javolution.xml.jaxb.common.test.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the javolution.xml.jaxb.common.test.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: javolution.xml.jaxb.common.test.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestCommonElement }
     * 
     */
    public TestCommonElement createTestCommonElement() {
        return new TestCommonElement();
    }

    /**
     * Create an instance of {@link TestCommonRoot }
     * 
     */
    public TestCommonRoot createTestCommonRoot() {
        return new TestCommonRoot();
    }

    /**
     * Create an instance of {@link TestChoiceElement }
     * 
     */
    public TestChoiceElement createTestChoiceElement() {
        return new TestChoiceElement();
    }

    /**
     * Create an instance of {@link TestChoiceElementB }
     * 
     */
    public TestChoiceElementB createTestChoiceElementB() {
        return new TestChoiceElementB();
    }

    /**
     * Create an instance of {@link TestChoiceElementA }
     * 
     */
    public TestChoiceElementA createTestChoiceElementA() {
        return new TestChoiceElementA();
    }

    /**
     * Create an instance of {@link TestCommonBase }
     * 
     */
    public TestCommonBase createTestCommonBase() {
        return new TestCommonBase();
    }

}
