//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 09:13:55 PM EDT 
//


package javolution.xml.jaxb.common.test.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for testDateFormatElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="testDateFormatElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="testDateElement" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="testDateTimeElement" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="testDurationElement" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *         &lt;element name="testTimeElement" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testDateFormatElement", propOrder = {
    "testDateElement",
    "testDateTimeElement",
    "testDurationElement",
    "testTimeElement"
})
public class TestDateFormatElement {

    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar testDateElement;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar testDateTimeElement;
    protected Duration testDurationElement;
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar testTimeElement;

    /**
     * Gets the value of the testDateElement property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTestDateElement() {
        return testDateElement;
    }

    /**
     * Sets the value of the testDateElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTestDateElement(XMLGregorianCalendar value) {
        this.testDateElement = value;
    }

    /**
     * Gets the value of the testDateTimeElement property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTestDateTimeElement() {
        return testDateTimeElement;
    }

    /**
     * Sets the value of the testDateTimeElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTestDateTimeElement(XMLGregorianCalendar value) {
        this.testDateTimeElement = value;
    }

    /**
     * Gets the value of the testDurationElement property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getTestDurationElement() {
        return testDurationElement;
    }

    /**
     * Sets the value of the testDurationElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setTestDurationElement(Duration value) {
        this.testDurationElement = value;
    }

    /**
     * Gets the value of the testTimeElement property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTestTimeElement() {
        return testTimeElement;
    }

    /**
     * Sets the value of the testTimeElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTestTimeElement(XMLGregorianCalendar value) {
        this.testTimeElement = value;
    }

}
