//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.02 at 09:04:17 PM EDT 
//


package javolution.xml.jaxb.common.test.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for testChoiceElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="testChoiceElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="testChoiceElementA" type="{http://javolution.org/xml/schema/javolution-common}testChoiceElementA"/>
 *         &lt;element name="testChoiceElementB" type="{http://javolution.org/xml/schema/javolution-common}testChoiceElementB"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testChoiceElement", propOrder = {
    "testChoiceElementAOrTestChoiceElementB"
})
public class TestChoiceElement {

    @XmlElements({
        @XmlElement(name = "testChoiceElementA", type = TestChoiceElementA.class),
        @XmlElement(name = "testChoiceElementB", type = TestChoiceElementB.class)
    })
    protected List<TestCommonBase> testChoiceElementAOrTestChoiceElementB;

    /**
     * Gets the value of the testChoiceElementAOrTestChoiceElementB property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testChoiceElementAOrTestChoiceElementB property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestChoiceElementAOrTestChoiceElementB().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestChoiceElementA }
     * {@link TestChoiceElementB }
     * 
     * 
     */
    public List<TestCommonBase> getTestChoiceElementAOrTestChoiceElementB() {
        if (testChoiceElementAOrTestChoiceElementB == null) {
            testChoiceElementAOrTestChoiceElementB = new ArrayList<TestCommonBase>();
        }
        return this.testChoiceElementAOrTestChoiceElementB;
    }

}
