//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.02 at 09:04:17 PM EDT 
//


package javolution.xml.jaxb.common.test.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for testChoiceElementB complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="testChoiceElementB">
 *   &lt;complexContent>
 *     &lt;extension base="{http://javolution.org/xml/schema/javolution-common}testCommonBase">
 *       &lt;sequence>
 *         &lt;element name="testChoiceB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testChoiceElementB", propOrder = {
    "testChoiceB"
})
public class TestChoiceElementB
    extends TestCommonBase
{

    protected String testChoiceB;

    /**
     * Gets the value of the testChoiceB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestChoiceB() {
        return testChoiceB;
    }

    /**
     * Sets the value of the testChoiceB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestChoiceB(String value) {
        this.testChoiceB = value;
    }

}
