//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.16 at 02:51:34 PM EDT 
//


package javolution.xml.jaxb.common.test.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for testBinaryElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="testBinaryElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="testBase64Element" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="testHexElement" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testBinaryElement", propOrder = {
    "testBase64Element",
    "testHexElement"
})
public class TestBinaryElement {

    protected byte[] testBase64Element;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] testHexElement;

    /**
     * Gets the value of the testBase64Element property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getTestBase64Element() {
        return testBase64Element;
    }

    /**
     * Sets the value of the testBase64Element property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setTestBase64Element(byte[] value) {
        this.testBase64Element = value;
    }

    /**
     * Gets the value of the testHexElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getTestHexElement() {
        return testHexElement;
    }

    /**
     * Sets the value of the testHexElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestHexElement(byte[] value) {
        this.testHexElement = value;
    }

}
