//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.27 at 01:51:33 PM EDT 
//


package javolution.xml.jaxb.test.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the javolution.xml.jaxb.test.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: javolution.xml.jaxb.test.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestRoot }
     * 
     */
    public TestRoot createTestRoot() {
        return new TestRoot();
    }

    /**
     * Create an instance of {@link TestElement }
     * 
     */
    public TestElement createTestElement() {
        return new TestElement();
    }

    /**
     * Create an instance of {@link TestValidationElement }
     * 
     */
    public TestValidationElement createTestValidationElement() {
        return new TestValidationElement();
    }

    /**
     * Create an instance of {@link TestAttributeElement }
     * 
     */
    public TestAttributeElement createTestAttributeElement() {
        return new TestAttributeElement();
    }

    /**
     * Create an instance of {@link TestUnboundedWrapperElement }
     * 
     */
    public TestUnboundedWrapperElement createTestUnboundedWrapperElement() {
        return new TestUnboundedWrapperElement();
    }

    /**
     * Create an instance of {@link TestBoundedWrapperElement }
     * 
     */
    public TestBoundedWrapperElement createTestBoundedWrapperElement() {
        return new TestBoundedWrapperElement();
    }

    /**
     * Create an instance of {@link TestCommonElement }
     * 
     */
    public TestCommonElement createTestCommonElement() {
        return new TestCommonElement();
    }

    /**
     * Create an instance of {@link TestCommonRoot }
     * 
     */
    public TestCommonRoot createTestCommonRoot() {
        return new TestCommonRoot();
    }

}
