//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.02 at 09:04:17 PM EDT 
//


package javolution.xml.jaxb.test.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for testEnumElement.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="testEnumElement">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TEST_ENUM_ONE"/>
 *     &lt;enumeration value="TEST_ENUM_TWO"/>
 *     &lt;enumeration value="TEST_ENUM_THREE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "testEnumElement")
@XmlEnum
public enum TestEnumElement {

    TEST_ENUM_ONE,
    TEST_ENUM_TWO,
    TEST_ENUM_THREE;

    public String value() {
        return name();
    }

    public static TestEnumElement fromValue(String v) {
        return valueOf(v);
    }

}
