//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.02 at 09:04:17 PM EDT 
//


package javolution.xml.jaxb.test.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for testUnboundedWrapperElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="testUnboundedWrapperElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="testElement" type="{http://javolution.org/xml/schema/javolution}testElement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="testValidationElement" type="{http://javolution.org/xml/schema/javolution}testValidationElement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="testAttributeElement" type="{http://javolution.org/xml/schema/javolution}testAttributeElement" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testUnboundedWrapperElement", propOrder = {
    "testElement",
    "testValidationElement",
    "testAttributeElement"
})
public class TestUnboundedWrapperElement {

    protected List<TestElement> testElement;
    protected List<TestValidationElement> testValidationElement;
    protected List<TestAttributeElement> testAttributeElement;

    /**
     * Gets the value of the testElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestElement }
     * 
     * 
     */
    public List<TestElement> getTestElement() {
        if (testElement == null) {
            testElement = new ArrayList<TestElement>();
        }
        return this.testElement;
    }

    /**
     * Gets the value of the testValidationElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testValidationElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestValidationElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestValidationElement }
     * 
     * 
     */
    public List<TestValidationElement> getTestValidationElement() {
        if (testValidationElement == null) {
            testValidationElement = new ArrayList<TestValidationElement>();
        }
        return this.testValidationElement;
    }

    /**
     * Gets the value of the testAttributeElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testAttributeElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestAttributeElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestAttributeElement }
     * 
     * 
     */
    public List<TestAttributeElement> getTestAttributeElement() {
        if (testAttributeElement == null) {
            testAttributeElement = new ArrayList<TestAttributeElement>();
        }
        return this.testAttributeElement;
    }

}
