//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 09:13:55 PM EDT 
//


package javolution.xml.jaxb.test.schema;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for testAttributeElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="testAttributeElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="stringAttribute" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="intAttribute" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="longAttribute" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="booleanAttribute" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="floatAttribute" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="doubleAttribute" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="dateAttribute" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="shortAttribute" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="byteAttribute" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="decimalAttribute" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testAttributeElement")
public class TestAttributeElement {

    @XmlAttribute(name = "stringAttribute", required = true)
    protected String stringAttribute;
    @XmlAttribute(name = "intAttribute")
    protected Integer intAttribute;
    @XmlAttribute(name = "longAttribute")
    protected Long longAttribute;
    @XmlAttribute(name = "booleanAttribute")
    protected Boolean booleanAttribute;
    @XmlAttribute(name = "floatAttribute")
    protected Float floatAttribute;
    @XmlAttribute(name = "doubleAttribute")
    protected Double doubleAttribute;
    @XmlAttribute(name = "dateAttribute")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateAttribute;
    @XmlAttribute(name = "shortAttribute")
    protected Short shortAttribute;
    @XmlAttribute(name = "byteAttribute")
    protected Byte byteAttribute;
    @XmlAttribute(name = "decimalAttribute")
    protected BigDecimal decimalAttribute;

    /**
     * Gets the value of the stringAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStringAttribute() {
        return stringAttribute;
    }

    /**
     * Sets the value of the stringAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStringAttribute(String value) {
        this.stringAttribute = value;
    }

    /**
     * Gets the value of the intAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIntAttribute() {
        return intAttribute;
    }

    /**
     * Sets the value of the intAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIntAttribute(Integer value) {
        this.intAttribute = value;
    }

    /**
     * Gets the value of the longAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLongAttribute() {
        return longAttribute;
    }

    /**
     * Sets the value of the longAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLongAttribute(Long value) {
        this.longAttribute = value;
    }

    /**
     * Gets the value of the booleanAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBooleanAttribute() {
        return booleanAttribute;
    }

    /**
     * Sets the value of the booleanAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBooleanAttribute(Boolean value) {
        this.booleanAttribute = value;
    }

    /**
     * Gets the value of the floatAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFloatAttribute() {
        return floatAttribute;
    }

    /**
     * Sets the value of the floatAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFloatAttribute(Float value) {
        this.floatAttribute = value;
    }

    /**
     * Gets the value of the doubleAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDoubleAttribute() {
        return doubleAttribute;
    }

    /**
     * Sets the value of the doubleAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDoubleAttribute(Double value) {
        this.doubleAttribute = value;
    }

    /**
     * Gets the value of the dateAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateAttribute() {
        return dateAttribute;
    }

    /**
     * Sets the value of the dateAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateAttribute(XMLGregorianCalendar value) {
        this.dateAttribute = value;
    }

    /**
     * Gets the value of the shortAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getShortAttribute() {
        return shortAttribute;
    }

    /**
     * Sets the value of the shortAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setShortAttribute(Short value) {
        this.shortAttribute = value;
    }

    /**
     * Gets the value of the byteAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getByteAttribute() {
        return byteAttribute;
    }

    /**
     * Sets the value of the byteAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setByteAttribute(Byte value) {
        this.byteAttribute = value;
    }

    /**
     * Gets the value of the decimalAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDecimalAttribute() {
        return decimalAttribute;
    }

    /**
     * Sets the value of the decimalAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDecimalAttribute(BigDecimal value) {
        this.decimalAttribute = value;
    }

}
